# Generated by Django 3.0.3 on 2020-02-17 19:31

from django.db import migrations, models
import smms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to=smms.models.path_to_images)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
