# Generated by Django 3.0.3 on 2020-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smms', '0002_auto_20200224_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalsalesprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
