# Generated by Django 3.0.3 on 2020-02-17 20:09

from django.db import migrations, models
import smms.models


class Migration(migrations.Migration):

    dependencies = [
        ('smms', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=smms.models.path_to_images),
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='supplier',
            field=models.CharField(default='yale food', max_length=100),
            preserve_default=False,
        ),
    ]
