# Generated by Django 3.0.3 on 2020-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smms', '0003_auto_20200217_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
